# Generated by Django 4.0.4 on 2022-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_alter_report_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
