# Generated by Django 4.0.4 on 2022-05-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_commentnotification_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
