# Generated by Django 4.0.4 on 2022-05-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_likenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
