# Generated by Django 4.0.4 on 2022-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0015_countpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='countpost',
            name='count_comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countpost',
            name='count_like',
            field=models.IntegerField(null=True),
        ),
    ]
